### ISSUE TITLE
How can I scan a page with multiple barcodes?

### ISSUE THREAD

**Issue by GeekiTutorials** [brettatoms/zbar-ctypes#4]
This wrapper has been great for me once I got everything configured correctly for Windows. However I am writing a program for work that will be using Python to scan shipping pages with multiple barcodes. When I use Zbar by itself in the command prompt it scans a full page just fine, but through the Zbar wrapper in Python I am only able to scan single barcode images. Do you have any recommendations? Thanks

**Comment by brettatoms** [comment]
I honestly don't know.  I haven't used this in a long time and I can't remember why it would or wouldn't scan full pages.  This line seems to imply it will return all the codes on a page so I don't know it wouldn't work: 

https://github.com/brettatoms/zbar-ctypes/blob/master/zbar/zbar.py#L115

**Comment by GeekiTutorials** [comment]
Ive been staring at that exact same line scratching my head wondering the
same thing. I have tried multiple documents with more than one barcode and
it just returns an empty list [ ]. If i isolate a single barcode into a
different image it reads just fine. Honestly ive been pulling my hair out
trying to get python to work with zbar for a while now for a work project
and you have brought me 99 percent of the way there. No other wrappers ever
worked. Anyways, i know this is an old project for you, i was double
checking out of desperation

**Comment by brettatoms** [comment]
If you do figure it out then please comment back here or send a PR.

**Comment by GeekiTutorials** [comment]
I was able to solve the issue. I changed line 110 in Zbar.py:
from 

> if decoded != 1:
> to 
> if decoded < 1:

and I added one line at the bottom of the Ctypes.py:

> libzbar.zbar_symbol_next.restype = POINTER(zbar_symbol_t)

Now it can read multiple barcodes just fine.
